# Generated by Django 4.1.7 on 2023-05-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pontos',
            fields=[
                ('id_ponto', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nome_ponto', models.CharField(max_length=250)),
                ('preco', models.IntegerField(default=0)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
